export const TOOLKIT_OPTIONS = 'TOOLKIT_OPTIONS';
export const TOOLKIT_STORAGE_DRIVER = 'TOOLKIT_STORAGE_DRIVER';
export const TOOLKIT_AUDIT_REPOSITORY = 'TOOLKIT_AUDIT_REPOSITORY';
export const TOOLKIT_OAUTH_CLIENT_REPOSITORY = 'TOOLKIT_OAUTH_CLIENT_REPOSITORY';